ncsudo: required
language: python
python:
- 3.7-dev
install:
- pip install pipenv
- pipenv install --dev
script:
- echo bla
#script:
#- pipenv run pytest
deploy:
  provider: pypi
  user: lukecodewalker
  password:
    secure: DYEUCY18TL+9VAqciGVzxhWBjfOyZJxJ9jcR6RyKpa/ky8L0RZukXzdwUetRJfys0s5fX4sQzjCMMK8479e8I/og2qAIBl6bq0IHgWJbHlSsx4ugyMIrW03Pd86k7EHs/pUZUjIsf9SROlltnqSkKZRHTOPKrDQSzBUP2+/WHXZN3zG6zz7LqjncRxH2k97Hea5LNpzU+Qnbt2hQGWAkLEboUv6Uf3OBfPyXPUlNHfRxej1QEtOyFPpE1lX9Y0+muYpMQVHPJr6NbMUFOm3bNEhiAs+8TbK19wtd3P02lEeuxxZK3i1ddiHPuC9WeQr/rx1qTQyb+lRibPeVz6Uo1opOIju9LIcr0elQ+J/RtS9rdqq13gqAUgTnECpOsiZt8MWBDdMUXA4Oaf4ix+WRjhSjDL9zFtIR6tXZe4BF7nRXBhdlCCrT0NwUWS1RJTiXn/+uSDb5S2/WZHlAxVxn7ByRFc7MM06+1fy1Qs+F5YiOAEsegaiZNlje5vGfQ6qPpXbGWCJN+F09v4UoXjYeMN7V//pkj/WRrlGV6XqUw6sWycDY03wkv8eVkiqtcNfpM3Bf2du7cy7K66tNif+bbDJvaQVvbG4dR9wZYmqJT0+qRGQglMx2QttZyUWuU80CLNKrSKyKW+I5bURJzc85FZu0qGR4PU/viaW3lhxrJcw=
  on:
    tags: true
  distributions: bdist_wheel
